# ComfyUI/custom_nodes/minicpmv4_llamacpp/__init__.py
from .loader import NODE_CLASS_MAPPINGS as LOADER_MAP, NODE_DISPLAY_NAME_MAPPINGS as LOADER_NAME
from .prompt_utils import NODE_CLASS_MAPPINGS as PROMPT_MAP, NODE_DISPLAY_NAME_MAPPINGS as PROMPT_NAME
from .vision_infer import NODE_CLASS_MAPPINGS as INFER_MAP, NODE_DISPLAY_NAME_MAPPINGS as INFER_NAME

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LOADER_MAP)
NODE_CLASS_MAPPINGS.update(PROMPT_MAP)
NODE_CLASS_MAPPINGS.update(INFER_MAP)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LOADER_NAME)
NODE_DISPLAY_NAME_MAPPINGS.update(PROMPT_NAME)
NODE_DISPLAY_NAME_MAPPINGS.update(INFER_NAME)
